# Copyright: (c) 2024, Black-Cockpit <hasnimehdi@outlook.com>
# MIT License (see LICENSE or https://opensource.org/licenses/MIT)
from __future__ import (absolute_import, division, print_function)

import traceback

from ansible.module_utils.basic import AnsibleModule, missing_required_lib
from gvm.connections import UnixSocketConnection

from ..module_utils.models.ScheduleRecurrenceModel import ScheduleRecurrenceModel
from ..module_utils.models.ScheduleModel import ScheduleModel
from ..module_utils.exceptions.ResourceInUseError import ResourceInUseError
from ..module_utils.models.GvmAdminCredentialsModel import GvmAdminCredentialsModel
from ..module_utils.libs.GvmManager import GvmManager

__metaclass__ = type
LIB_IMP_ERR = None
try:
    from gvm.protocols.gmp.requests.v225 import CredentialType

    HAS_LIB = True
except ModuleNotFoundError or NameError:
    HAS_LIB = False
    LIB_IMP_ERR = traceback.format_exc()

DOCUMENTATION = r'''
---
module: gvm_schedule

short_description: Manage schedules in Greenbone Vulnerability Manager (GVM)

version_added: "1.0.0"

description:
    - This module allows you to create, update, and delete schedules in GVM.
    - It supports defining recurrence patterns and setting time zones for the schedules.

author:
    - Hasni Mehdi (@hasnimehdi91)
    - hasnimehdi@outlook.com

options:
    socket_path:
        description: 
            - GVM socket path, default: /run/gvmd/gvmd.sock
        required: false
        type: str
        default: /run/gvmd/gvmd.sock
    gvm_username:
        description: 
            - GVM admin username: default: admin.
        required: false
        type: str
        default: admin
    gvm_password:
        description: 
            - GVM admin password: default: admin.
        required: false
        type: str
        default: admin
    name:
        description:
            - The name of the schedule.
        required: true
        type: str
    comment:
        description:
            - A comment or description for the schedule.
        required: false
        type: str
    time_zone:
        description:
            - The time zone for the schedule.
            - Default is "UTC".
        required: false
        type: str
        default: "UTC"
        choices:    ['Africa/Abidjan',
                    'Africa/Accra',
                    'Africa/Addis_Ababa',
                    'Africa/Algiers',
                    'Africa/Asmara',
                    'Africa/Asmera',
                    'Africa/Bamako',
                    'Africa/Bangui',
                    'Africa/Banjul',
                    'Africa/Bissau',
                    'Africa/Blantyre',
                    'Africa/Brazzaville',
                    'Africa/Bujumbura',
                    'Africa/Cairo',
                    'Africa/Casablanca',
                    'Africa/Ceuta',
                    'Africa/Conakry',
                    'Africa/Dakar',
                    'Africa/Dar_es_Salaam',
                    'Africa/Djibouti',
                    'Africa/Douala',
                    'Africa/El_Aaiun',
                    'Africa/Freetown',
                    'Africa/Gaborone',
                    'Africa/Harare',
                    'Africa/Johannesburg',
                    'Africa/Juba',
                    'Africa/Kampala',
                    'Africa/Khartoum',
                    'Africa/Kigali',
                    'Africa/Kinshasa',
                    'Africa/Lagos',
                    'Africa/Libreville',
                    'Africa/Lome',
                    'Africa/Luanda',
                    'Africa/Lubumbashi',
                    'Africa/Lusaka',
                    'Africa/Malabo',
                    'Africa/Maputo',
                    'Africa/Maseru',
                    'Africa/Mbabane',
                    'Africa/Mogadishu',
                    'Africa/Monrovia',
                    'Africa/Nairobi',
                    'Africa/Ndjamena',
                    'Africa/Niamey',
                    'Africa/Nouakchott',
                    'Africa/Ouagadougou',
                    'Africa/Porto-Novo',
                    'Africa/Sao_Tome',
                    'Africa/Timbuktu',
                    'Africa/Tripoli',
                    'Africa/Tunis',
                    'Africa/Windhoek',
                    'America/Adak',
                    'America/Anchorage',
                    'America/Anguilla',
                    'America/Antigua',
                    'America/Araguaina',
                    'America/Argentina/Buenos_Aires',
                    'America/Argentina/Catamarca',
                    'America/Argentina/ComodRivadavia',
                    'America/Argentina/Cordoba',
                    'America/Argentina/Jujuy',
                    'America/Argentina/La_Rioja',
                    'America/Argentina/Mendoza',
                    'America/Argentina/Rio_Gallegos',
                    'America/Argentina/Salta',
                    'America/Argentina/San_Juan',
                    'America/Argentina/San_Luis',
                    'America/Argentina/Tucuman',
                    'America/Argentina/Ushuaia',
                    'America/Aruba',
                    'America/Asuncion',
                    'America/Atikokan',
                    'America/Atka',
                    'America/Bahia',
                    'America/Bahia_Banderas',
                    'America/Barbados',
                    'America/Belem',
                    'America/Belize',
                    'America/Blanc-Sablon',
                    'America/Boa_Vista',
                    'America/Bogota',
                    'America/Boise',
                    'America/Buenos_Aires',
                    'America/Cambridge_Bay',
                    'America/Campo_Grande',
                    'America/Cancun',
                    'America/Caracas',
                    'America/Catamarca',
                    'America/Cayenne',
                    'America/Cayman',
                    'America/Chicago',
                    'America/Chihuahua',
                    'America/Ciudad_Juarez',
                    'America/Coral_Harbour',
                    'America/Cordoba',
                    'America/Costa_Rica',
                    'America/Creston',
                    'America/Cuiaba',
                    'America/Curacao',
                    'America/Danmarkshavn',
                    'America/Dawson',
                    'America/Dawson_Creek',
                    'America/Denver',
                    'America/Detroit',
                    'America/Dominica',
                    'America/Edmonton',
                    'America/Eirunepe',
                    'America/El_Salvador',
                    'America/Ensenada',
                    'America/Fort_Nelson',
                    'America/Fort_Wayne',
                    'America/Fortaleza',
                    'America/Glace_Bay',
                    'America/Godthab',
                    'America/Goose_Bay',
                    'America/Grand_Turk',
                    'America/Grenada',
                    'America/Guadeloupe',
                    'America/Guatemala',
                    'America/Guayaquil',
                    'America/Guyana',
                    'America/Halifax',
                    'America/Havana',
                    'America/Hermosillo',
                    'America/Indiana/Indianapolis',
                    'America/Indiana/Knox',
                    'America/Indiana/Marengo',
                    'America/Indiana/Petersburg',
                    'America/Indiana/Tell_City',
                    'America/Indiana/Vevay',
                    'America/Indiana/Vincennes',
                    'America/Indiana/Winamac',
                    'America/Indianapolis',
                    'America/Inuvik',
                    'America/Iqaluit',
                    'America/Jamaica',
                    'America/Jujuy',
                    'America/Juneau',
                    'America/Kentucky/Louisville',
                    'America/Kentucky/Monticello',
                    'America/Knox_IN',
                    'America/Kralendijk',
                    'America/La_Paz',
                    'America/Lima',
                    'America/Los_Angeles',
                    'America/Louisville',
                    'America/Lower_Princes',
                    'America/Maceio',
                    'America/Managua',
                    'America/Manaus',
                    'America/Marigot',
                    'America/Martinique',
                    'America/Matamoros',
                    'America/Mazatlan',
                    'America/Mendoza',
                    'America/Menominee',
                    'America/Merida',
                    'America/Metlakatla',
                    'America/Mexico_City',
                    'America/Miquelon',
                    'America/Moncton',
                    'America/Monterrey',
                    'America/Montevideo',
                    'America/Montreal',
                    'America/Montserrat',
                    'America/Nassau',
                    'America/New_York',
                    'America/Nipigon',
                    'America/Nome',
                    'America/Noronha',
                    'America/North_Dakota/Beulah',
                    'America/North_Dakota/Center',
                    'America/North_Dakota/New_Salem',
                    'America/Nuuk',
                    'America/Ojinaga',
                    'America/Panama',
                    'America/Pangnirtung',
                    'America/Paramaribo',
                    'America/Phoenix',
                    'America/Port-au-Prince',
                    'America/Port_of_Spain',
                    'America/Porto_Acre',
                    'America/Porto_Velho',
                    'America/Puerto_Rico',
                    'America/Punta_Arenas',
                    'America/Rainy_River',
                    'America/Rankin_Inlet',
                    'America/Recife',
                    'America/Regina',
                    'America/Resolute',
                    'America/Rio_Branco',
                    'America/Rosario',
                    'America/Santa_Isabel',
                    'America/Santarem',
                    'America/Santiago',
                    'America/Santo_Domingo',
                    'America/Sao_Paulo',
                    'America/Scoresbysund',
                    'America/Shiprock',
                    'America/Sitka',
                    'America/St_Barthelemy',
                    'America/St_Johns',
                    'America/St_Kitts',
                    'America/St_Lucia',
                    'America/St_Thomas',
                    'America/St_Vincent',
                    'America/Swift_Current',
                    'America/Tegucigalpa',
                    'America/Thule',
                    'America/Thunder_Bay',
                    'America/Tijuana',
                    'America/Toronto',
                    'America/Tortola',
                    'America/Vancouver',
                    'America/Virgin',
                    'America/Whitehorse',
                    'America/Winnipeg',
                    'America/Yakutat',
                    'America/Yellowknife',
                    'Antarctica/Casey',
                    'Antarctica/Davis',
                    'Antarctica/DumontDUrville',
                    'Antarctica/Macquarie',
                    'Antarctica/Mawson',
                    'Antarctica/McMurdo',
                    'Antarctica/Palmer',
                    'Antarctica/Rothera',
                    'Antarctica/South_Pole',
                    'Antarctica/Syowa',
                    'Antarctica/Troll',
                    'Antarctica/Vostok',
                    'Arctic/Longyearbyen',
                    'Asia/Aden',
                    'Asia/Almaty',
                    'Asia/Amman',
                    'Asia/Anadyr',
                    'Asia/Aqtau',
                    'Asia/Aqtobe',
                    'Asia/Ashgabat',
                    'Asia/Ashkhabad',
                    'Asia/Atyrau',
                    'Asia/Baghdad',
                    'Asia/Bahrain',
                    'Asia/Baku',
                    'Asia/Bangkok',
                    'Asia/Barnaul',
                    'Asia/Beirut',
                    'Asia/Bishkek',
                    'Asia/Brunei',
                    'Asia/Calcutta',
                    'Asia/Chita',
                    'Asia/Choibalsan',
                    'Asia/Chongqing',
                    'Asia/Chungking',
                    'Asia/Colombo',
                    'Asia/Dacca',
                    'Asia/Damascus',
                    'Asia/Dhaka',
                    'Asia/Dili',
                    'Asia/Dubai',
                    'Asia/Dushanbe',
                    'Asia/Famagusta',
                    'Asia/Gaza',
                    'Asia/Harbin',
                    'Asia/Hebron',
                    'Asia/Ho_Chi_Minh',
                    'Asia/Hong_Kong',
                    'Asia/Hovd',
                    'Asia/Irkutsk',
                    'Asia/Istanbul',
                    'Asia/Jakarta',
                    'Asia/Jayapura',
                    'Asia/Jerusalem',
                    'Asia/Kabul',
                    'Asia/Kamchatka',
                    'Asia/Karachi',
                    'Asia/Kashgar',
                    'Asia/Kathmandu',
                    'Asia/Katmandu',
                    'Asia/Khandyga',
                    'Asia/Kolkata',
                    'Asia/Krasnoyarsk',
                    'Asia/Kuala_Lumpur',
                    'Asia/Kuching',
                    'Asia/Kuwait',
                    'Asia/Macao',
                    'Asia/Macau',
                    'Asia/Magadan',
                    'Asia/Makassar',
                    'Asia/Manila',
                    'Asia/Muscat',
                    'Asia/Nicosia',
                    'Asia/Novokuznetsk',
                    'Asia/Novosibirsk',
                    'Asia/Omsk',
                    'Asia/Oral',
                    'Asia/Phnom_Penh',
                    'Asia/Pontianak',
                    'Asia/Pyongyang',
                    'Asia/Qatar',
                    'Asia/Qostanay',
                    'Asia/Qyzylorda',
                    'Asia/Rangoon',
                    'Asia/Riyadh',
                    'Asia/Saigon',
                    'Asia/Sakhalin',
                    'Asia/Samarkand',
                    'Asia/Seoul',
                    'Asia/Shanghai',
                    'Asia/Singapore',
                    'Asia/Srednekolymsk',
                    'Asia/Taipei',
                    'Asia/Tashkent',
                    'Asia/Tbilisi',
                    'Asia/Tehran',
                    'Asia/Tel_Aviv',
                    'Asia/Thimbu',
                    'Asia/Thimphu',
                    'Asia/Tokyo',
                    'Asia/Tomsk',
                    'Asia/Ujung_Pandang',
                    'Asia/Ulaanbaatar',
                    'Asia/Ulan_Bator',
                    'Asia/Urumqi',
                    'Asia/Ust-Nera',
                    'Asia/Vientiane',
                    'Asia/Vladivostok',
                    'Asia/Yakutsk',
                    'Asia/Yangon',
                    'Asia/Yekaterinburg',
                    'Asia/Yerevan',
                    'Atlantic/Azores',
                    'Atlantic/Bermuda',
                    'Atlantic/Canary',
                    'Atlantic/Cape_Verde',
                    'Atlantic/Faeroe',
                    'Atlantic/Faroe',
                    'Atlantic/Jan_Mayen',
                    'Atlantic/Madeira',
                    'Atlantic/Reykjavik',
                    'Atlantic/South_Georgia',
                    'Atlantic/St_Helena',
                    'Atlantic/Stanley',
                    'Australia/ACT',
                    'Australia/Adelaide',
                    'Australia/Brisbane',
                    'Australia/Broken_Hill',
                    'Australia/Canberra',
                    'Australia/Currie',
                    'Australia/Darwin',
                    'Australia/Eucla',
                    'Australia/Hobart',
                    'Australia/LHI',
                    'Australia/Lindeman',
                    'Australia/Lord_Howe',
                    'Australia/Melbourne',
                    'Australia/NSW',
                    'Australia/North',
                    'Australia/Perth',
                    'Australia/Queensland',
                    'Australia/South',
                    'Australia/Sydney',
                    'Australia/Tasmania',
                    'Australia/Victoria',
                    'Australia/West',
                    'Australia/Yancowinna',
                    'Brazil/Acre',
                    'Brazil/DeNoronha',
                    'Brazil/East',
                    'Brazil/West',
                    'CET',
                    'CST6CDT',
                    'Canada/Atlantic',
                    'Canada/Central',
                    'Canada/Eastern',
                    'Canada/Mountain',
                    'Canada/Newfoundland',
                    'Canada/Pacific',
                    'Canada/Saskatchewan',
                    'Canada/Yukon',
                    'Chile/Continental',
                    'Chile/EasterIsland',
                    'Cuba',
                    'EET',
                    'EST',
                    'EST5EDT',
                    'Egypt',
                    'Eire',
                    'Etc/GMT',
                    'Etc/GMT+0',
                    'Etc/GMT+1',
                    'Etc/GMT+10',
                    'Etc/GMT+11',
                    'Etc/GMT+12',
                    'Etc/GMT+2',
                    'Etc/GMT+3',
                    'Etc/GMT+4',
                    'Etc/GMT+5',
                    'Etc/GMT+6',
                    'Etc/GMT+7',
                    'Etc/GMT+8',
                    'Etc/GMT+9',
                    'Etc/GMT-0',
                    'Etc/GMT-1',
                    'Etc/GMT-10',
                    'Etc/GMT-11',
                    'Etc/GMT-12',
                    'Etc/GMT-13',
                    'Etc/GMT-14',
                    'Etc/GMT-2',
                    'Etc/GMT-3',
                    'Etc/GMT-4',
                    'Etc/GMT-5',
                    'Etc/GMT-6',
                    'Etc/GMT-7',
                    'Etc/GMT-8',
                    'Etc/GMT-9',
                    'Etc/GMT0',
                    'Etc/Greenwich',
                    'Etc/UCT',
                    'Etc/UTC',
                    'Etc/Universal',
                    'Etc/Zulu',
                    'Europe/Amsterdam',
                    'Europe/Andorra',
                    'Europe/Astrakhan',
                    'Europe/Athens',
                    'Europe/Belfast',
                    'Europe/Belgrade',
                    'Europe/Berlin',
                    'Europe/Bratislava',
                    'Europe/Brussels',
                    'Europe/Bucharest',
                    'Europe/Budapest',
                    'Europe/Busingen',
                    'Europe/Chisinau',
                    'Europe/Copenhagen',
                    'Europe/Dublin',
                    'Europe/Gibraltar',
                    'Europe/Guernsey',
                    'Europe/Helsinki',
                    'Europe/Isle_of_Man',
                    'Europe/Istanbul',
                    'Europe/Jersey',
                    'Europe/Kaliningrad',
                    'Europe/Kiev',
                    'Europe/Kirov',
                    'Europe/Kyiv',
                    'Europe/Lisbon',
                    'Europe/Ljubljana',
                    'Europe/London',
                    'Europe/Luxembourg',
                    'Europe/Madrid',
                    'Europe/Malta',
                    'Europe/Mariehamn',
                    'Europe/Minsk',
                    'Europe/Monaco',
                    'Europe/Moscow',
                    'Europe/Nicosia',
                    'Europe/Oslo',
                    'Europe/Paris',
                    'Europe/Podgorica',
                    'Europe/Prague',
                    'Europe/Riga',
                    'Europe/Rome',
                    'Europe/Samara',
                    'Europe/San_Marino',
                    'Europe/Sarajevo',
                    'Europe/Saratov',
                    'Europe/Simferopol',
                    'Europe/Skopje',
                    'Europe/Sofia',
                    'Europe/Stockholm',
                    'Europe/Tallinn',
                    'Europe/Tirane',
                    'Europe/Tiraspol',
                    'Europe/Ulyanovsk',
                    'Europe/Uzhgorod',
                    'Europe/Vaduz',
                    'Europe/Vatican',
                    'Europe/Vienna',
                    'Europe/Vilnius',
                    'Europe/Volgograd',
                    'Europe/Warsaw',
                    'Europe/Zagreb',
                    'Europe/Zaporozhye',
                    'Europe/Zurich',
                    'GB',
                    'GB-Eire',
                    'GMT',
                    'GMT+0',
                    'GMT-0',
                    'GMT0',
                    'Greenwich',
                    'HST',
                    'Hongkong',
                    'Iceland',
                    'Indian/Antananarivo',
                    'Indian/Chagos',
                    'Indian/Christmas',
                    'Indian/Cocos',
                    'Indian/Comoro',
                    'Indian/Kerguelen',
                    'Indian/Mahe',
                    'Indian/Maldives',
                    'Indian/Mauritius',
                    'Indian/Mayotte',
                    'Indian/Reunion',
                    'Iran',
                    'Israel',
                    'Jamaica',
                    'Japan',
                    'Kwajalein',
                    'Libya',
                    'MET',
                    'MST',
                    'MST7MDT',
                    'Mexico/BajaNorte',
                    'Mexico/BajaSur',
                    'Mexico/General',
                    'NZ',
                    'NZ-CHAT',
                    'Navajo',
                    'PRC',
                    'PST8PDT',
                    'Pacific/Apia',
                    'Pacific/Auckland',
                    'Pacific/Bougainville',
                    'Pacific/Chatham',
                    'Pacific/Chuuk',
                    'Pacific/Easter',
                    'Pacific/Efate',
                    'Pacific/Enderbury',
                    'Pacific/Fakaofo',
                    'Pacific/Fiji',
                    'Pacific/Funafuti',
                    'Pacific/Galapagos',
                    'Pacific/Gambier',
                    'Pacific/Guadalcanal',
                    'Pacific/Guam',
                    'Pacific/Honolulu',
                    'Pacific/Johnston',
                    'Pacific/Kanton',
                    'Pacific/Kiritimati',
                    'Pacific/Kosrae',
                    'Pacific/Kwajalein',
                    'Pacific/Majuro',
                    'Pacific/Marquesas',
                    'Pacific/Midway',
                    'Pacific/Nauru',
                    'Pacific/Niue',
                    'Pacific/Norfolk',
                    'Pacific/Noumea',
                    'Pacific/Pago_Pago',
                    'Pacific/Palau',
                    'Pacific/Pitcairn',
                    'Pacific/Pohnpei',
                    'Pacific/Ponape',
                    'Pacific/Port_Moresby',
                    'Pacific/Rarotonga',
                    'Pacific/Saipan',
                    'Pacific/Samoa',
                    'Pacific/Tahiti',
                    'Pacific/Tarawa',
                    'Pacific/Tongatapu',
                    'Pacific/Truk',
                    'Pacific/Wake',
                    'Pacific/Wallis',
                    'Pacific/Yap',
                    'Poland',
                    'Portugal',
                    'ROC',
                    'ROK',
                    'Singapore',
                    'Turkey',
                    'UCT',
                    'US/Alaska',
                    'US/Aleutian',
                    'US/Arizona',
                    'US/Central',
                    'US/East-Indiana',
                    'US/Eastern',
                    'US/Hawaii',
                    'US/Indiana-Starke',
                    'US/Michigan',
                    'US/Mountain',
                    'US/Pacific',
                    'US/Samoa',
                    'UTC',
                    'Universal',
                    'W-SU',
                    'WET',
                    'Zulu']
    first_run_at:
        description:
            - The date and time of the first run in the format "Aug 12 2023 00:00".
        required: true
        type: str
    run_until:
        description:
            - The date and time when the schedule should stop running.
            - Format is "Aug 12 2024 00:00". If not provided, the schedule runs indefinitely.
        required: false
        type: str
    recurrence:
        description:
            - Defines the recurrence pattern for the schedule.
        type: dict
        required: false
        suboptions:
            frequency:
                description:
                    - The frequency of the recurrence.
                    - Options are "DAILY", "WEEKLY", "MONTHLY", "YEARLY".
                type: str
                required: false
                choices: ["HOURLY","DAILY","WEEKLY","MONTHLY","YEARLY"]
            interval:
                description:
                    - The interval between recurrences.
                type: int
                required: false
            days_of_week:
                description:
                    - Days of the week for weekly schedules.
                    - Use two-letter abbreviations, e.g., ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].
                type: list
                elements: str
                required: false
                choices: ['We', 'Th', 'Fr', 'Sa', 'Su', 'Mo', 'Tu']
            days_of_month:
                description:
                    - Days of the month for monthly schedules (from 1 to 31).
                type: list
                elements: int
                required: false
                choices: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
    state:
        description:
            - Desired state of the schedule.
            - Can be "present" or "absent".
        required: false
        type: str
        default: present
        choices: ['present', 'absent']
'''

EXAMPLES = r'''
---
- name: Create a weekly Saturday schedule
  gvm_schedule:
    socket_path: "/run/gvmd/gvmd.sock"
    gvm_username: "admin"
    gvm_password: "admin"
    name: "weekly_saturday_schedule"
    comment: "Weekly Saturday schedule"
    time_zone: "UTC"
    first_run_at: "Aug 12 2023 00:00"
    recurrence:
      frequency: "WEEKLY"
      interval: 1
      days_of_week:
        - "Sa"
    state: present

- name: Update an existing schedule
  gvm_schedule:
    socket_path: "/run/gvmd/gvmd.sock"
    gvm_username: "admin"
    gvm_password: "admin"
    name: "weekly_saturday_schedule"
    comment: "Updated weekly Saturday schedule"
    time_zone: "UTC"
    first_run_at: "Aug 12 2023 00:00"
    recurrence:
      frequency: "WEEKLY"
      interval: 1
      days_of_week:
        - "Sa"
    state: present

- name: Delete a schedule
  gvm_schedule:
    socket_path: "/run/gvmd/gvmd.sock"
    gvm_username: "admin"
    gvm_password: "admin"
    name: "weekly_saturday_schedule"
    state: absent
'''

RETURN = r'''
# These are the attributes that can be returned by the module.
changed:
    description: The state of the task.
    type: bool
    returned: always
msg:
    description: Error message if applicable.
    type: str
    returned: when_failed
failed:
    description: Indicate if the task failed
    type: bool
    returned: always
'''


def run_module():
    """
    gvm_schedule module
    Returns:
    """

    # gvm_schedule module arguments
    module_args = dict(
        socket_path=dict(type='str', required=False, default='/run/gvmd/gvmd.sock'),
        gvm_username=dict(type='str', required=False, default='admin'),
        gvm_password=dict(type='str', required=False, default='admin', no_log=True),
        name=dict(type='str', required=True),
        comment=dict(type='str', required=False),
        first_run_at=dict(type='str', required=True),
        run_until=dict(type='str', required=False, default=None),
        time_zone=dict(
            type='str',
            required=False,
            default='UTC',
            choices=['Africa/Abidjan',
                     'Africa/Accra',
                     'Africa/Addis_Ababa',
                     'Africa/Algiers',
                     'Africa/Asmara',
                     'Africa/Asmera',
                     'Africa/Bamako',
                     'Africa/Bangui',
                     'Africa/Banjul',
                     'Africa/Bissau',
                     'Africa/Blantyre',
                     'Africa/Brazzaville',
                     'Africa/Bujumbura',
                     'Africa/Cairo',
                     'Africa/Casablanca',
                     'Africa/Ceuta',
                     'Africa/Conakry',
                     'Africa/Dakar',
                     'Africa/Dar_es_Salaam',
                     'Africa/Djibouti',
                     'Africa/Douala',
                     'Africa/El_Aaiun',
                     'Africa/Freetown',
                     'Africa/Gaborone',
                     'Africa/Harare',
                     'Africa/Johannesburg',
                     'Africa/Juba',
                     'Africa/Kampala',
                     'Africa/Khartoum',
                     'Africa/Kigali',
                     'Africa/Kinshasa',
                     'Africa/Lagos',
                     'Africa/Libreville',
                     'Africa/Lome',
                     'Africa/Luanda',
                     'Africa/Lubumbashi',
                     'Africa/Lusaka',
                     'Africa/Malabo',
                     'Africa/Maputo',
                     'Africa/Maseru',
                     'Africa/Mbabane',
                     'Africa/Mogadishu',
                     'Africa/Monrovia',
                     'Africa/Nairobi',
                     'Africa/Ndjamena',
                     'Africa/Niamey',
                     'Africa/Nouakchott',
                     'Africa/Ouagadougou',
                     'Africa/Porto-Novo',
                     'Africa/Sao_Tome',
                     'Africa/Timbuktu',
                     'Africa/Tripoli',
                     'Africa/Tunis',
                     'Africa/Windhoek',
                     'America/Adak',
                     'America/Anchorage',
                     'America/Anguilla',
                     'America/Antigua',
                     'America/Araguaina',
                     'America/Argentina/Buenos_Aires',
                     'America/Argentina/Catamarca',
                     'America/Argentina/ComodRivadavia',
                     'America/Argentina/Cordoba',
                     'America/Argentina/Jujuy',
                     'America/Argentina/La_Rioja',
                     'America/Argentina/Mendoza',
                     'America/Argentina/Rio_Gallegos',
                     'America/Argentina/Salta',
                     'America/Argentina/San_Juan',
                     'America/Argentina/San_Luis',
                     'America/Argentina/Tucuman',
                     'America/Argentina/Ushuaia',
                     'America/Aruba',
                     'America/Asuncion',
                     'America/Atikokan',
                     'America/Atka',
                     'America/Bahia',
                     'America/Bahia_Banderas',
                     'America/Barbados',
                     'America/Belem',
                     'America/Belize',
                     'America/Blanc-Sablon',
                     'America/Boa_Vista',
                     'America/Bogota',
                     'America/Boise',
                     'America/Buenos_Aires',
                     'America/Cambridge_Bay',
                     'America/Campo_Grande',
                     'America/Cancun',
                     'America/Caracas',
                     'America/Catamarca',
                     'America/Cayenne',
                     'America/Cayman',
                     'America/Chicago',
                     'America/Chihuahua',
                     'America/Ciudad_Juarez',
                     'America/Coral_Harbour',
                     'America/Cordoba',
                     'America/Costa_Rica',
                     'America/Creston',
                     'America/Cuiaba',
                     'America/Curacao',
                     'America/Danmarkshavn',
                     'America/Dawson',
                     'America/Dawson_Creek',
                     'America/Denver',
                     'America/Detroit',
                     'America/Dominica',
                     'America/Edmonton',
                     'America/Eirunepe',
                     'America/El_Salvador',
                     'America/Ensenada',
                     'America/Fort_Nelson',
                     'America/Fort_Wayne',
                     'America/Fortaleza',
                     'America/Glace_Bay',
                     'America/Godthab',
                     'America/Goose_Bay',
                     'America/Grand_Turk',
                     'America/Grenada',
                     'America/Guadeloupe',
                     'America/Guatemala',
                     'America/Guayaquil',
                     'America/Guyana',
                     'America/Halifax',
                     'America/Havana',
                     'America/Hermosillo',
                     'America/Indiana/Indianapolis',
                     'America/Indiana/Knox',
                     'America/Indiana/Marengo',
                     'America/Indiana/Petersburg',
                     'America/Indiana/Tell_City',
                     'America/Indiana/Vevay',
                     'America/Indiana/Vincennes',
                     'America/Indiana/Winamac',
                     'America/Indianapolis',
                     'America/Inuvik',
                     'America/Iqaluit',
                     'America/Jamaica',
                     'America/Jujuy',
                     'America/Juneau',
                     'America/Kentucky/Louisville',
                     'America/Kentucky/Monticello',
                     'America/Knox_IN',
                     'America/Kralendijk',
                     'America/La_Paz',
                     'America/Lima',
                     'America/Los_Angeles',
                     'America/Louisville',
                     'America/Lower_Princes',
                     'America/Maceio',
                     'America/Managua',
                     'America/Manaus',
                     'America/Marigot',
                     'America/Martinique',
                     'America/Matamoros',
                     'America/Mazatlan',
                     'America/Mendoza',
                     'America/Menominee',
                     'America/Merida',
                     'America/Metlakatla',
                     'America/Mexico_City',
                     'America/Miquelon',
                     'America/Moncton',
                     'America/Monterrey',
                     'America/Montevideo',
                     'America/Montreal',
                     'America/Montserrat',
                     'America/Nassau',
                     'America/New_York',
                     'America/Nipigon',
                     'America/Nome',
                     'America/Noronha',
                     'America/North_Dakota/Beulah',
                     'America/North_Dakota/Center',
                     'America/North_Dakota/New_Salem',
                     'America/Nuuk',
                     'America/Ojinaga',
                     'America/Panama',
                     'America/Pangnirtung',
                     'America/Paramaribo',
                     'America/Phoenix',
                     'America/Port-au-Prince',
                     'America/Port_of_Spain',
                     'America/Porto_Acre',
                     'America/Porto_Velho',
                     'America/Puerto_Rico',
                     'America/Punta_Arenas',
                     'America/Rainy_River',
                     'America/Rankin_Inlet',
                     'America/Recife',
                     'America/Regina',
                     'America/Resolute',
                     'America/Rio_Branco',
                     'America/Rosario',
                     'America/Santa_Isabel',
                     'America/Santarem',
                     'America/Santiago',
                     'America/Santo_Domingo',
                     'America/Sao_Paulo',
                     'America/Scoresbysund',
                     'America/Shiprock',
                     'America/Sitka',
                     'America/St_Barthelemy',
                     'America/St_Johns',
                     'America/St_Kitts',
                     'America/St_Lucia',
                     'America/St_Thomas',
                     'America/St_Vincent',
                     'America/Swift_Current',
                     'America/Tegucigalpa',
                     'America/Thule',
                     'America/Thunder_Bay',
                     'America/Tijuana',
                     'America/Toronto',
                     'America/Tortola',
                     'America/Vancouver',
                     'America/Virgin',
                     'America/Whitehorse',
                     'America/Winnipeg',
                     'America/Yakutat',
                     'America/Yellowknife',
                     'Antarctica/Casey',
                     'Antarctica/Davis',
                     'Antarctica/DumontDUrville',
                     'Antarctica/Macquarie',
                     'Antarctica/Mawson',
                     'Antarctica/McMurdo',
                     'Antarctica/Palmer',
                     'Antarctica/Rothera',
                     'Antarctica/South_Pole',
                     'Antarctica/Syowa',
                     'Antarctica/Troll',
                     'Antarctica/Vostok',
                     'Arctic/Longyearbyen',
                     'Asia/Aden',
                     'Asia/Almaty',
                     'Asia/Amman',
                     'Asia/Anadyr',
                     'Asia/Aqtau',
                     'Asia/Aqtobe',
                     'Asia/Ashgabat',
                     'Asia/Ashkhabad',
                     'Asia/Atyrau',
                     'Asia/Baghdad',
                     'Asia/Bahrain',
                     'Asia/Baku',
                     'Asia/Bangkok',
                     'Asia/Barnaul',
                     'Asia/Beirut',
                     'Asia/Bishkek',
                     'Asia/Brunei',
                     'Asia/Calcutta',
                     'Asia/Chita',
                     'Asia/Choibalsan',
                     'Asia/Chongqing',
                     'Asia/Chungking',
                     'Asia/Colombo',
                     'Asia/Dacca',
                     'Asia/Damascus',
                     'Asia/Dhaka',
                     'Asia/Dili',
                     'Asia/Dubai',
                     'Asia/Dushanbe',
                     'Asia/Famagusta',
                     'Asia/Gaza',
                     'Asia/Harbin',
                     'Asia/Hebron',
                     'Asia/Ho_Chi_Minh',
                     'Asia/Hong_Kong',
                     'Asia/Hovd',
                     'Asia/Irkutsk',
                     'Asia/Istanbul',
                     'Asia/Jakarta',
                     'Asia/Jayapura',
                     'Asia/Jerusalem',
                     'Asia/Kabul',
                     'Asia/Kamchatka',
                     'Asia/Karachi',
                     'Asia/Kashgar',
                     'Asia/Kathmandu',
                     'Asia/Katmandu',
                     'Asia/Khandyga',
                     'Asia/Kolkata',
                     'Asia/Krasnoyarsk',
                     'Asia/Kuala_Lumpur',
                     'Asia/Kuching',
                     'Asia/Kuwait',
                     'Asia/Macao',
                     'Asia/Macau',
                     'Asia/Magadan',
                     'Asia/Makassar',
                     'Asia/Manila',
                     'Asia/Muscat',
                     'Asia/Nicosia',
                     'Asia/Novokuznetsk',
                     'Asia/Novosibirsk',
                     'Asia/Omsk',
                     'Asia/Oral',
                     'Asia/Phnom_Penh',
                     'Asia/Pontianak',
                     'Asia/Pyongyang',
                     'Asia/Qatar',
                     'Asia/Qostanay',
                     'Asia/Qyzylorda',
                     'Asia/Rangoon',
                     'Asia/Riyadh',
                     'Asia/Saigon',
                     'Asia/Sakhalin',
                     'Asia/Samarkand',
                     'Asia/Seoul',
                     'Asia/Shanghai',
                     'Asia/Singapore',
                     'Asia/Srednekolymsk',
                     'Asia/Taipei',
                     'Asia/Tashkent',
                     'Asia/Tbilisi',
                     'Asia/Tehran',
                     'Asia/Tel_Aviv',
                     'Asia/Thimbu',
                     'Asia/Thimphu',
                     'Asia/Tokyo',
                     'Asia/Tomsk',
                     'Asia/Ujung_Pandang',
                     'Asia/Ulaanbaatar',
                     'Asia/Ulan_Bator',
                     'Asia/Urumqi',
                     'Asia/Ust-Nera',
                     'Asia/Vientiane',
                     'Asia/Vladivostok',
                     'Asia/Yakutsk',
                     'Asia/Yangon',
                     'Asia/Yekaterinburg',
                     'Asia/Yerevan',
                     'Atlantic/Azores',
                     'Atlantic/Bermuda',
                     'Atlantic/Canary',
                     'Atlantic/Cape_Verde',
                     'Atlantic/Faeroe',
                     'Atlantic/Faroe',
                     'Atlantic/Jan_Mayen',
                     'Atlantic/Madeira',
                     'Atlantic/Reykjavik',
                     'Atlantic/South_Georgia',
                     'Atlantic/St_Helena',
                     'Atlantic/Stanley',
                     'Australia/ACT',
                     'Australia/Adelaide',
                     'Australia/Brisbane',
                     'Australia/Broken_Hill',
                     'Australia/Canberra',
                     'Australia/Currie',
                     'Australia/Darwin',
                     'Australia/Eucla',
                     'Australia/Hobart',
                     'Australia/LHI',
                     'Australia/Lindeman',
                     'Australia/Lord_Howe',
                     'Australia/Melbourne',
                     'Australia/NSW',
                     'Australia/North',
                     'Australia/Perth',
                     'Australia/Queensland',
                     'Australia/South',
                     'Australia/Sydney',
                     'Australia/Tasmania',
                     'Australia/Victoria',
                     'Australia/West',
                     'Australia/Yancowinna',
                     'Brazil/Acre',
                     'Brazil/DeNoronha',
                     'Brazil/East',
                     'Brazil/West',
                     'CET',
                     'CST6CDT',
                     'Canada/Atlantic',
                     'Canada/Central',
                     'Canada/Eastern',
                     'Canada/Mountain',
                     'Canada/Newfoundland',
                     'Canada/Pacific',
                     'Canada/Saskatchewan',
                     'Canada/Yukon',
                     'Chile/Continental',
                     'Chile/EasterIsland',
                     'Cuba',
                     'EET',
                     'EST',
                     'EST5EDT',
                     'Egypt',
                     'Eire',
                     'Etc/GMT',
                     'Etc/GMT+0',
                     'Etc/GMT+1',
                     'Etc/GMT+10',
                     'Etc/GMT+11',
                     'Etc/GMT+12',
                     'Etc/GMT+2',
                     'Etc/GMT+3',
                     'Etc/GMT+4',
                     'Etc/GMT+5',
                     'Etc/GMT+6',
                     'Etc/GMT+7',
                     'Etc/GMT+8',
                     'Etc/GMT+9',
                     'Etc/GMT-0',
                     'Etc/GMT-1',
                     'Etc/GMT-10',
                     'Etc/GMT-11',
                     'Etc/GMT-12',
                     'Etc/GMT-13',
                     'Etc/GMT-14',
                     'Etc/GMT-2',
                     'Etc/GMT-3',
                     'Etc/GMT-4',
                     'Etc/GMT-5',
                     'Etc/GMT-6',
                     'Etc/GMT-7',
                     'Etc/GMT-8',
                     'Etc/GMT-9',
                     'Etc/GMT0',
                     'Etc/Greenwich',
                     'Etc/UCT',
                     'Etc/UTC',
                     'Etc/Universal',
                     'Etc/Zulu',
                     'Europe/Amsterdam',
                     'Europe/Andorra',
                     'Europe/Astrakhan',
                     'Europe/Athens',
                     'Europe/Belfast',
                     'Europe/Belgrade',
                     'Europe/Berlin',
                     'Europe/Bratislava',
                     'Europe/Brussels',
                     'Europe/Bucharest',
                     'Europe/Budapest',
                     'Europe/Busingen',
                     'Europe/Chisinau',
                     'Europe/Copenhagen',
                     'Europe/Dublin',
                     'Europe/Gibraltar',
                     'Europe/Guernsey',
                     'Europe/Helsinki',
                     'Europe/Isle_of_Man',
                     'Europe/Istanbul',
                     'Europe/Jersey',
                     'Europe/Kaliningrad',
                     'Europe/Kiev',
                     'Europe/Kirov',
                     'Europe/Kyiv',
                     'Europe/Lisbon',
                     'Europe/Ljubljana',
                     'Europe/London',
                     'Europe/Luxembourg',
                     'Europe/Madrid',
                     'Europe/Malta',
                     'Europe/Mariehamn',
                     'Europe/Minsk',
                     'Europe/Monaco',
                     'Europe/Moscow',
                     'Europe/Nicosia',
                     'Europe/Oslo',
                     'Europe/Paris',
                     'Europe/Podgorica',
                     'Europe/Prague',
                     'Europe/Riga',
                     'Europe/Rome',
                     'Europe/Samara',
                     'Europe/San_Marino',
                     'Europe/Sarajevo',
                     'Europe/Saratov',
                     'Europe/Simferopol',
                     'Europe/Skopje',
                     'Europe/Sofia',
                     'Europe/Stockholm',
                     'Europe/Tallinn',
                     'Europe/Tirane',
                     'Europe/Tiraspol',
                     'Europe/Ulyanovsk',
                     'Europe/Uzhgorod',
                     'Europe/Vaduz',
                     'Europe/Vatican',
                     'Europe/Vienna',
                     'Europe/Vilnius',
                     'Europe/Volgograd',
                     'Europe/Warsaw',
                     'Europe/Zagreb',
                     'Europe/Zaporozhye',
                     'Europe/Zurich',
                     'GB',
                     'GB-Eire',
                     'GMT',
                     'GMT+0',
                     'GMT-0',
                     'GMT0',
                     'Greenwich',
                     'HST',
                     'Hongkong',
                     'Iceland',
                     'Indian/Antananarivo',
                     'Indian/Chagos',
                     'Indian/Christmas',
                     'Indian/Cocos',
                     'Indian/Comoro',
                     'Indian/Kerguelen',
                     'Indian/Mahe',
                     'Indian/Maldives',
                     'Indian/Mauritius',
                     'Indian/Mayotte',
                     'Indian/Reunion',
                     'Iran',
                     'Israel',
                     'Jamaica',
                     'Japan',
                     'Kwajalein',
                     'Libya',
                     'MET',
                     'MST',
                     'MST7MDT',
                     'Mexico/BajaNorte',
                     'Mexico/BajaSur',
                     'Mexico/General',
                     'NZ',
                     'NZ-CHAT',
                     'Navajo',
                     'PRC',
                     'PST8PDT',
                     'Pacific/Apia',
                     'Pacific/Auckland',
                     'Pacific/Bougainville',
                     'Pacific/Chatham',
                     'Pacific/Chuuk',
                     'Pacific/Easter',
                     'Pacific/Efate',
                     'Pacific/Enderbury',
                     'Pacific/Fakaofo',
                     'Pacific/Fiji',
                     'Pacific/Funafuti',
                     'Pacific/Galapagos',
                     'Pacific/Gambier',
                     'Pacific/Guadalcanal',
                     'Pacific/Guam',
                     'Pacific/Honolulu',
                     'Pacific/Johnston',
                     'Pacific/Kanton',
                     'Pacific/Kiritimati',
                     'Pacific/Kosrae',
                     'Pacific/Kwajalein',
                     'Pacific/Majuro',
                     'Pacific/Marquesas',
                     'Pacific/Midway',
                     'Pacific/Nauru',
                     'Pacific/Niue',
                     'Pacific/Norfolk',
                     'Pacific/Noumea',
                     'Pacific/Pago_Pago',
                     'Pacific/Palau',
                     'Pacific/Pitcairn',
                     'Pacific/Pohnpei',
                     'Pacific/Ponape',
                     'Pacific/Port_Moresby',
                     'Pacific/Rarotonga',
                     'Pacific/Saipan',
                     'Pacific/Samoa',
                     'Pacific/Tahiti',
                     'Pacific/Tarawa',
                     'Pacific/Tongatapu',
                     'Pacific/Truk',
                     'Pacific/Wake',
                     'Pacific/Wallis',
                     'Pacific/Yap',
                     'Poland',
                     'Portugal',
                     'ROC',
                     'ROK',
                     'Singapore',
                     'Turkey',
                     'UCT',
                     'US/Alaska',
                     'US/Aleutian',
                     'US/Arizona',
                     'US/Central',
                     'US/East-Indiana',
                     'US/Eastern',
                     'US/Hawaii',
                     'US/Indiana-Starke',
                     'US/Michigan',
                     'US/Mountain',
                     'US/Pacific',
                     'US/Samoa',
                     'UTC',
                     'Universal',
                     'W-SU',
                     'WET',
                     'Zulu'],
            description='The time zone for the schedule. Default is "UTC".'
        ),
        recurrence=dict(
            type='dict',
            required=False,
            options=dict(
                frequency=dict(type='str', required=False, choices=["HOURLY", "DAILY", "WEEKLY", "MONTHLY", "YEARLY"]),
                interval=dict(type='int', required=False, default=0),
                days_of_week=dict(type='list', elements='str', required=False, default=[]),
                days_of_month=dict(type='list', elements='int', required=False, default=[]),
            )
        ),
        state=dict(type='str', required=False, default='present', choices=['absent', 'present'])
    )

    # module result initialization
    result = dict(
        changed=False,
        failed=False,
    )

    # module initialization
    gvm_module = AnsibleModule(
        argument_spec=module_args,
        supports_check_mode=False
    )

    # Validate socket path
    if gvm_module.params['socket_path'] is None or gvm_module.params['socket_path'] == '' or gvm_module.params[
        'socket_path'].isspace():
        gvm_module.fail_json(msg='socket_path is required')

    # Validate GVM username
    if gvm_module.params['gvm_username'] is None or gvm_module.params['gvm_username'] == '' or gvm_module.params[
        'gvm_username'].isspace():
        gvm_module.fail_json(msg='gvm_username is required')

    # Validate GVM username
    if gvm_module.params['gvm_password'] is None or gvm_module.params['gvm_password'] == '' or gvm_module.params[
        'gvm_password'].isspace():
        gvm_module.fail_json(msg='gvm_username is required')

    if not HAS_LIB:
        gvm_module.fail_json(msg=missing_required_lib("gvm"), exception=LIB_IMP_ERR)

    try:
        # Initialize GVM manager
        manager = GvmManager(UnixSocketConnection(path=gvm_module.params['socket_path']),
                             GvmAdminCredentialsModel(gvm_module.params['gvm_username'],
                                                      gvm_module.params['gvm_password']))

        recurrence = None

        # Initialize recurrence
        if gvm_module.params['recurrence'] is not None:
            recurrence = ScheduleRecurrenceModel(frequency=gvm_module.params['recurrence']['frequency'],
                                                 interval=gvm_module.params['recurrence']['interval'],
                                                 days_of_week=gvm_module.params['recurrence']['days_of_week'],
                                                 days_of_month=gvm_module.params['recurrence']['days_of_month'])

        # Initialize schedule
        schedule = ScheduleModel(name=gvm_module.params['name'], comment=gvm_module.params['comment'],
                                 time_zone=gvm_module.params['time_zone'],
                                 first_run_at=gvm_module.params['first_run_at'],
                                 run_until=gvm_module.params['run_until'], recurrence=recurrence)

        if gvm_module.params['state'] == 'present':
            execution_result = manager.create_or_schedules(schedules=[schedule])
            result['changed'] = execution_result.changed
            if execution_result.warning_message is not None and execution_result.warning_message != '':
                gvm_module.warn(execution_result.warning_message)
        else:
            execution_result = manager.delete_schedules(schedules=[schedule])
            result['changed'] = execution_result.changed
    except ResourceInUseError as e:
        result['failed'] = True
        result['msg'] = str(e)
        gvm_module.fail_json(**result)
    except Exception as e:
        result['failed'] = True
        result['msg'] = str(f'Failed to manage GVM schedule {e}')
        gvm_module.fail_json(**result)

    # Exit with result
    gvm_module.exit_json(**result)


def main():
    """
    Execute gvm_schedule module
    Returns:

    """
    run_module()


if __name__ == '__main__':
    """
    Module main
    """
    main()
